### ISSUE TITLE
Fixer le sensor de conductivité pour qu’il corresponde au plug du pitre

### ISSUE THREAD

**Issue by chenevas** [chenevas/BioreactorPlanning#10]

**Comment by aliceleydier** [comment]
apparement il faut regarder la fiche technique on a pas besoins des trois câbles parce qu'il y en a un de référence (redemander a Quentin quand même) et donc souder les cables sur un plug in de pH et le mettre sur une carte pH.

**Comment by aliceleydier** [comment]
Acheter les plugs

**Comment by aliceleydier** [comment]
Pour l'instant valeur constante: inverser fils ?

**Comment by aliceleydier** [comment]
Marche toujours pas en inversant les fils: doit pas être la même façon de fonctionner que ph-metre

**Comment by aliceleydier** [comment]
Demander a quentin

**Comment by aliceleydier** [comment]
Response: on peut pas utiliser la carte du ph pour le conductimetre: il y a un circuit déduit pour la V4
