### ISSUE TITLE
Faire ph metre pour Bior2

### ISSUE THREAD

**Issue by aliceleydier** [chenevas/BioreactorPlanning#30]

**Comment by chenevas** [comment]
On doit blinder les câbles pour éviter qu'il y ait  trop de bruits

**Comment by chenevas** [comment]
En attente de la réponse de Julien aussi non aller dans le centre commercial Holguines
https://www.google.com.co/maps/place/HOLGUINES+TRADE+CENTER/@3.3717635,-76.5420263,17z/data=!3m1!4b1!4m5!3m4!1s0x8e30a17a54ef6335:0xfe78c9cf44855e81!8m2!3d3.3717635!4d-76.5398376

**Comment by chenevas** [comment]
Toujours un problème de bruit après avoir mis un câble coaxial ... on doit aller prendre un autre connecteur chez Holguines pour voir si ça marche mieux.

**Comment by aliceleydier** [comment]
Ils avaient pas le connecteur ...

**Comment by aliceleydier** [comment]
Peut-Être que le ph-metre est cassé? (hypothèse de quentin)

**Comment by aliceleydier** [comment]
pbm avec le ph-mètre (testé avec AB15): pas stable du tout ...
