### ISSUE TITLE
documenter la différence entre les 26 premiers paramètres et les autres

### ISSUE THREAD

**Issue by aliceleydier** [chenevas/BioreactorPlanning#47]

**Comment by aliceleydier** [comment]
Les 26 premiers paramètres sont stockés dans la mémoire flash comme spécifié dans https://github.com/Bioreactor/Bioreactor_V3/blob/68da631cf961d2e5d1f3bf61228e5c8cbbfd1d6a/Arduino/BioMain/Logger.ino#L14. Normallement les 26 premiers paramètres sont des paramètres variables durant l'expérience. Température, pH, conductivité, ... et ne devrait pas contenir des valeurs de callibration !!! Je pense que Quentin a revu cela pour la version 4 (à confirmer)

**Comment by chenevas** [comment]
P22 of the manual
