### ISSUE TITLE
Raspberry pie et pbm avec screen

### ISSUE THREAD

**Issue by chenevas** [chenevas/BioreactorPlanning#7]

**Comment by aliceleydier** [comment]
il faut mettre l’alimentation par micro usb, mettre le cable ethernet au modem et mettre le câble qu’on met normalement sur l’ordi sur le raspberry et accéder à l’interface par navigateur avec l’adresse IP

**Comment by chenevas** [comment]
Les commandes ne sont pas à jours je ne sais pas comment le faire marcher..

**Comment by aliceleydier** [comment]
Julien nous aide

**Comment by chenevas** [comment]
Semble marcher correctement les deux pi sont connectés à internet et reçoivent les logs
